# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55ac000f24c76945f5af30168d6e446a8e05db673cd8c2db99ecdcb18df7c0ee462e3e2b292c34059fd857bcf797d5f836c427f52d811e1f7a0efa54fb3f7979

test:
  secret_key_base: 7441e08f0617b5deecfef0d41b6087a37142853628d35606d461e4bb5187e499056a5b3663e1b1ceac8a3365750a020c31d2f09cdb38a7a587438175ab4d0d3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
